### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by ofirkris** [sunniesuhyoung/DST#1]
Hello, Amazing work!
Can you share some trained weights for evaluation and testing purpose?

**Comment by sunniesuhyoung** [comment]
Hi, do you mean the content, warp, and regularization weights? I personally like using content_weight=8, warp_weight=0.5, and reg_weight=50 as I put in ```job_example.sh```!

**Comment by zwfcrazy** [comment]
The style transfer part optimizes online, it does not need any trained weights. (that's why it takes about 6 minutes to generate an image)
The feature extraction part requires imagenet pretrained VGGnet weights, which will be automatically downloaded by Pytorch when running for the first time.
