### ISSUE TITLE
Inference time of the model

### ISSUE THREAD

**Issue by Nerdyvedi** [sunniesuhyoung/DST#3]
Hi, 
Thank you for open sourcing such a great work.

Can you tell me the inference time of the model(end to end , including finding NBB and everything) ?
I would have checked it but seems like not all files have been added yet.

Thanks.

**Comment by sunniesuhyoung** [comment]
Running NBB with the --fast option takes a little over a minute, cleaning the points take a few seconds, and running DST with the default setting takes ~3 minutes, totaling to ~5 minutes on a GPU. I uploaded the NBB code that was missing, so you should be able to produce results now. Check out ```job_example.sh``` for example commands.
