### ISSUE TITLE
RuntimeError: solve_cuda: U(459,459) is zero, singular U.

### ISSUE THREAD

**Issue by ppjjee** [sunniesuhyoung/DST#7]
Thank you for sharing your amazing work!!

I'm trying to run the code using my own data, but singularity error happens every time.

I've checked that _zwfcrazy_ raised the same issue. In response to this, _RazvanRotaru_ said deleting the NBB and re-downloading it would help.
However, deleting NBB doesn't really help.

Could you help me to solve this problem?

Traceback (most recent call last):
  File "main.py", line 115, in <module>
    device=device)
  File "/root/DST/styletransfer.py", line 143, in DST
    new_im, content_im_warp, warp_field = apply_warp(new_im, [src_Kpts_aug], [dst_Kpts_aug], device, sharp=sharp_warp, im2=content_im_warp)
  File "/root/DST/warp.py", line 432, in apply_warp
    new_im, new_im2, warp_field = image_warp(new_im, dst, dst-src, device, sharp=sharp, img2=new_im2)
  File "/root/DST/warp.py", line 86, in image_warp
    w, v = solve_interpolation(dst_pts, flow_pts, device)
  File "/root/DST/warp.py", line 226, in solve_interpolation
    w_v, _ = torch.solve(rhs, lhs)
RuntimeError: solve_cuda: U(459,459) is zero, singular U.

**Comment by backnotprop** [comment]
fixed similar issue by using an older version of pytorch, 

example, 1.10.1 worked for me:
`!pip install torch==1.10.1+cu102 torchvision==0.11.2+cu102 torchaudio==0.10.1 -f https://download.pytorch.org/whl/torch_stable.html`

https://pytorch.org/get-started/previous-versions/

**Comment by ppjjee** [comment]
> fixed similar issue by using an older version of pytorch,
> 
> example, 1.10.1 worked for me: `!pip install torch==1.10.1+cu102 torchvision==0.11.2+cu102 torchaudio==0.10.1 -f https://download.pytorch.org/whl/torch_stable.html`
> 
> https://pytorch.org/get-started/previous-versions/

Thanks:)
This works for me too!
